MIMO/urls.py
from django.contrib import admin
from django.views.generic import RedirectView
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='/accounts/login/', permanent=True)),
    path('accounts/', include('accounts.urls')),
    path('main/', include('main.urls', namespace='main')),
    # path('groups/', include('groups.urls')),
]

accounts/urls.py
from django.urls import path
from .views import *

app_name = 'accounts'

urlpatterns = [
    path('signup/', SignUpView.as_view(), name = 'signup'),
    path('welcomepage/', welcomepage.as_view(), name='welcomepage'),  # 새로운 URL 패턴 추가
    path('login/', login_view, name = 'login'),
    path('logout/', logout_view, name ='logout'),
]

main/urls.py
from django.urls import path
from .views import *

app_name = 'main'

urlpatterns = [
    path('set-open-time/', set_open_time, name='set_open_time'),
    path('', main, name = 'main'),
    path('modify-open-time/', modify_time, name='modify_open_time'),
    path('message_list/', message_list, name = 'message_list'),
    path('message_create/', message_create, name = 'message_create'),
]

main/models.py
from django.db import models
from users.models import *
from django.utils import timezone

# 열람시간 저장 모델 + 각 유저마다 시간을 다르게 볼 수 있도록
class openTime(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    morning_time = models.TimeField(default='06:00:00')
    night_time = models.TimeField(default='23:00:00')

    def __str__(self):
        return f"모닝메세지: {self.morning_time}, 나잇메세지: {self.night_time}"

# 메세지 작성 모델
class Message(models.Model):
    nick = models.ForeignKey(Profile, on_delete=models.CASCADE)
    morning_mes = models.CharField(max_length=200)
    night_mes = models.CharField(max_length=200)
    created_at = models.DateTimeField('date published', default = timezone.now)

    def __str__(self):
        return f"{self.morning_mes}, {self.night_mes}"

main/forms.py
from django import forms
from .models import *

# 열람시간 폼
class OpenTimeForm(forms.ModelForm):
    class Meta:
        model = openTime
        fields = ['morning_time', 'night_time']
        widgets = {
            'morning_time': forms.TimeInput(attrs={'type': 'time'}),
            'night_time': forms.TimeInput(attrs={'type': 'time'}),
        }

# 메세지 폼
class MessageForm(forms.ModelForm):
    nickname = forms.CharField(label="닉네임", max_length=40)

    class Meta:
        model = Message
        fields = ['morning_mes', 'night_mes', 'nickname']
        labels = {
            'morning_mes': '아침메세지',
            'night_mes': '밤메세지',
        }

main/views.py
from datetime import datetime, timedelta
from django.utils.dateformat import DateFormat
from django.shortcuts import get_object_or_404, redirect, render
from rest_framework import status
from rest_framework.response import Response
from rest_framework.decorators import api_view
from .forms import *
from .models import *
from .serializers import openTimeSerializer

# 열람시간 설정 api
@api_view(['POST'])
def set_open_time(request):
    user = request.user
    serializer = openTimeSerializer(data = request.data)
    if serializer.is_valid():
        open_time, created = openTime.objects.get_or_create(user=user)
        open_time.morning_time = serializer.validated_data['morning_time']
        open_time.night_time = serializer.validated_data['night_time']
        open_time.save()
        return Response({'message': 'Open time set successfully'}, status=status.HTTP_200_OK)
    return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

# 열람시간 수정
def modify_time(request):
    user = request.user
    open_time, created = openTime.objects.get_or_create(user=user, defaults={'morning_time': '06:00:00', 'night_time': '23:00:00'})
    if request.method == 'POST':
        form = OpenTimeForm(request.POST, instance=open_time)
        if form.is_valid():
            form.save()
            return redirect('main:main')
    else:
        form = OpenTimeForm(instance=open_time)
    return render(request, 'main/modify_time.html', {'form': form})

# 메인화면을 렌더링 + 현재시간 띄우기 + 열람시간 띄우기 + 낮인지 밤인지 열람시간에 따라 메세지 확인 할 수 있는 지에 따라 템플릿에 다르게 표시하기
def main(request):
    user = request.user
    open_time = openTime.objects.filter(user=user).first()
    now = timezone.localtime(timezone.now())
    current_time = now.time()

    if open_time:
        morning_time = open_time.morning_time
        night_time = open_time.night_time
    else:
        morning_time = datetime.strptime('08:00:00', '%H:%M:%S').time()
        night_time = datetime.strptime('23:00:00', '%H:%M:%S').time()

    context = {
        'morning_time': morning_time,
        'night_time': night_time,
        'current_time' : now.strftime('%m월 %d일'), # 현재시간 표기
        'can_open_message' : False, # 메세지 열람가능 여부
    }

    # 디버깅을 위해 시간 출력
    print(f"현재 시간: {current_time}, 모닝 시간: {morning_time}, 나잇 시간: {night_time}")

    today = timezone.now().date()
    user_profile, created = Profile.objects.get_or_create(user=user)
    user_has_written_message = Message.objects.filter(nick=user_profile, created_at__date=today).exists()
    context['user_has_written_message'] = user_has_written_message

    # 아침 시간대(5시~12시)
    if datetime.strptime('05:00:00', '%H:%M:%S').time() <= current_time <= datetime.strptime('12:00:00', '%H:%M:%S').time():
        # 모닝(만약 9시로 지정했으면)
        if morning_time <= current_time <= (datetime.combine(now.date(), morning_time) + timedelta(hours=1)).time():
            if user_has_written_message:
                context['time_message'] = "아래의 카드를 확인하고 활기찬 아침을 시작해봐요."
            else:
                context['time_message'] = "오늘의 메시지를 등록하고 따뜻한 한 마디를 주고 받아보세요."
        # 모닝전(5시부터 9시 전까지는 이 문구가 뜨는 것)
        else:
            context['time_message'] = f"따뜻한 아침을 준비중이에요. 우리가 약속한 {morning_time.strftime('%I:%M %p')}에 만나요."
    # 밤 시간대(21시~24시 및 0시~4시)
    elif (datetime.strptime('21:00:00', '%H:%M:%S').time() <= current_time or current_time <= datetime.strptime('04:00:00', '%H:%M:%S').time()):
        # 나잇
        if night_time <= current_time <= (datetime.combine(now.date(), night_time) + timedelta(hours=1)).time():
            if user_has_written_message:
                context['time_message'] = "아래의 카드 하나를 선택해 따뜻한 한마디로 좋은 밤을 시작해봐요."
            else:
                context['time_message'] = "오늘의 메시지를 등록하고 따뜻한 한 마디를 주고 받아보세요."
        # 현재시간이 9시 이후라 else에도 해당하지않는데 elif에는 해당하나 if night_time~에 해당하지않는 경우
        elif current_time < night_time:
            if user_has_written_message:
                context['time_message'] = f"잠들기전, 우리가 약속한 {night_time.strftime('%I:%M %p')}에 만나요."
            else:
                context['time_message'] = "오늘의 메시지를 등록하고 따뜻한 한 마디를 주고 받아보세요."
    # 모닝 후, 나잇 전 (오전 12시(정오)부터 저녁 9시(21시))
    else:
        context['time_message'] = f"잠들기전, 우리가 약속한 {night_time.strftime('%I:%M %p')}에 만나요."

    # 선택적 열람을 위해
    if open_time:
        morning_time = open_time.morning_time
        night_time = open_time.night_time

        # 현재 시간 = 지정한 모닝메세지 열람시간 ~ 1h
        if morning_time <= current_time <= (datetime.combine(now.date(), morning_time) + timezone.timedelta(hours=1)).time():
            context['can_open_messages'] = True
        # 현재시간 = 지정한 나잇메세지 열람시간 ~ + 1h
        elif night_time <= current_time <= (datetime.combine(now.date(), night_time) + timezone.timedelta(hours=1)).time():
            context['can_open_messages'] = True

    return render(request, 'main/main.html', context)

# 메시지 열람하기
def message_list(request):
    today = timezone.now().date()
    messages = Message.objects.filter(created_at__date=today)
    return render(request, 'main/message_list.html', {'messages': messages})

# 메세지 작성하기
def message_create(request):
    if request.method == "POST":
        form = MessageForm(request.POST)
        if form.is_valid():
            nickname = form.cleaned_data['nickname']
            user_profile, created = Profile.objects.get_or_create(user=request.user)
            user_profile.nickname = nickname
            user_profile.save()

            message = form.save(commit=False)
            message.nick = user_profile

            message.save()
            return redirect('main:main')
        
    else:
        form = MessageForm()

    return render(request, 'main/message_create.html', {'form': form})

main/templates/main/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>MIMO</h1>
    {% if user_has_written_message %}
    <p>{{ current_time }} ✔ 메시지 등록</p>
    {% else %}
    <p>{{ current_time }} ✖ 메시지 등록</p>
    {% endif %}
    <p>{{ time_message }}</p>
    <p>모닝메세지: {{ morning_time }}</p>
    <p>나잇메세지: {{ night_time }}</p>
    <a href="{% url 'main:modify_open_time' %}">열람시간 변경</a>
    <a href="{% url 'accounts:login' %}">로그아웃</a>
    <hr>
    <a href="{% url 'main:message_create' %}">새 메세지 작성하기</a>
    <hr>
    {% if user_has_written_message %}
        {% if can_open_messages %}
            <a href="{% url 'main:message_list' %}">메시지 열람하기</a>
        {% else %}
            <p>지정된 시간에 열람하실 수 있습니다.</p>
        {% endif %}
    {% else %}
        <p>메시지를 등록 후 열람하실 수 있습니다.</p>
    {% endif %}
</body>
</html>




main/templates/main/message_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <p>{{ morning_time }}</p> <!-- context를 통해 접근 -->
    <p>{{ night_time }}</p> <!-- context를 통해 접근 -->
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit</button>
    </form>
</body>
</html>

main/templates/main/message_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <ul>
        {% for message in messages %}
            <li>
                <strong>Morning:</strong> {{ message.morning_mes }}<br>
                <strong>Night:</strong> {{ message.night_mes }}<br>
                <strong>작성 시간:</strong> {{ message.created_at }}<br>
                <strong class="nickname">{{ message.nick.nickname }}</strong>
            </li>
        {% endfor %}
    </ul>
    <hr>
    <a href="{% url 'main:main' %}">돌아가기</a>
</body>
</html>

main/templates/main/modify_time.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Modify Open Time</title>
</head>
<body>
    <h1>열람시간 수정하기</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">저장</button>
    </form>
    <a href="{% url 'main:main' %}">취소</a>
</body>
</html>

main/templates/main/update.html
<!DOCTYPE html>
<html>
<head>
    <title>Update Message</title>
</head>
<body>
    <h1>Update Message</h1>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Update</button>
    </form>

    <a href="{% url 'main:main' %}">Back to main</a>
</body>
</html>